"""agregar_numero_documento_movimientos

Revision ID: 03f25fc9dde0
Revises: 7a49675466b0
Create Date: 2025-04-09 10:34:51.833801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f25fc9dde0'
down_revision = '7a49675466b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numeroDocumento', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.drop_column('numeroDocumento')

    # ### end Alembic commands ###
