"""Agregar columnas stockMinimo y marca a Producto

Revision ID: 1d53e0a71220
Revises: 2cb665002733
Create Date: 2025-05-01 19:54:03.019776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d53e0a71220'
down_revision = '2cb665002733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stockMinimo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('marca', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('marca')
        batch_op.drop_column('stockMinimo')

    # ### end Alembic commands ###
