"""agregar_id_proveedor_movimientos

Revision ID: 2cb665002733
Revises: 03f25fc9dde0
Create Date: 2025-04-09 11:06:14.801946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb665002733'
down_revision = '03f25fc9dde0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idProveedor', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_movimiento_proveedor', 'proveedor', ['idProveedor'], ['idProveedor'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.drop_constraint('fk_movimiento_proveedor', type_='foreignkey')
        batch_op.drop_column('idProveedor')

    # ### end Alembic commands ###
