"""Agregar modelo Proveedor

Revision ID: 7a49675466b0
Revises: 
Create Date: 2025-04-08 14:41:49.862665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a49675466b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fechaFactura', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('cuitProveedor', sa.String(length=13), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.drop_column('cuitProveedor')
        batch_op.drop_column('fechaFactura')

    # ### end Alembic commands ###
